# Generated by Django 4.1.2 on 2022-11-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_requestitens_discount_alter_sale_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
