# Generated by Django 4.1.2 on 2022-11-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_sale_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': (('setar nfe', 'Usuario pode alterar NFE'), ('permissao 2', 'Permissão 2'), ('permissao 3', 'Permissão 3'))},
        ),
    ]
