# Generated by Django 4.1.2 on 2022-11-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_sale_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': (('setar_nfe', 'Usuario pode alterar NFE'), ('ver_dashboard', 'Pode visualizar o dashboard'), ('permissao3', 'Permissão 3'))},
        ),
    ]
