# Generated by Django 4.1.2 on 2022-10-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_person_salary_venda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documento',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='Venda',
            new_name='Sale',
        ),
    ]
