# Generated by Django 4.1.2 on 2022-11-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_remove_sale_products_requestitens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitens',
            name='product',
        ),
        migrations.RemoveField(
            model_name='requestitens',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='person',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='RequestItens',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
